### ISSUE TITLE
Covid 19 timeseries 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/public-health-prototype#34] opened 2020-03-10 20:47 UTC
make timeseries chart

**Comment by tiffanychu90** [comment] 2020-03-11 21:10
@hunterowens: If we're doing an ETL to push JHU's csv into an ESRI feature layer, can I ask for a 2nd ESRI feature layer?

1st layer: time-series data, long, at the city/county/province-level, where every row is a new date. 
* Columns to keep: confirmed, deaths, recovered. 
* Columns to derive: state abbrev for US, or province for other countries.

2nd layer: take the 1st layer, but keep only the most recent date at the city/county/province-level, so every row is a city/county's most recent counts. 
* Columns to keep: confirmed, deaths, recovered, state/province stuff
* Columns to derive: state/province total confirmed, state/province total deaths, and state/province total recovered, country total confirmed, country total deaths, country total recovered.
* Also derive for our dashboard: columns that show confirmed cases in the form of "1 in ____ in the US". Let's use a dictionary to define population to use as denominators: US pop (331M), CA pop (40M), LA pop (10M), OC pop (3.2M), Riverside (2.4M), San Bernardino pop (0.2M). 

I'll connect both layers to our AGOL dashboard.

Ref issue #31

**Comment by tiffanychu90** [comment] 2020-03-13 16:13
So, in light of JHU zeroing-out their entire county-level dataset, [GitHub issue here](https://github.com/CSSEGISandData/COVID-19/issues/382):
1. Scrape LA and other SCAG counties -- OC, Riverside, Ventura, San Bernardino (not scrapable, but also zero cases)
[LA](http://publichealth.lacounty.gov/media/Coronavirus/)
[OC](http://www.ochealthinfo.com/phs/about/epidasmt/epi/dip/prevention/novel_coronavirus)
[Riverside](https://www.rivcoph.org/coronavirus)
[Ventura](https://www.ventura.org/covid19/)
[San Bernardino](http://wp.sbcounty.gov/dph/coronavirus/)
[Imperial](http://www.icphd.org/health-information-and-resources/healthy-facts/covid-19/)
2. Use JHU county-level stuff from dates prior to 3/12/2020? 
3. State level data on our map
4. Change indicators on dashboard to show counts for individual SCAG counties, non-SCAG total, and CA total
5. Time-series for SCAG counties
6. Provide links to local public health sites

The ETL will have plop the last date of available JHU county CSV data on, drop everything state-level, so we avoid double-counting, and can still have a full time-series.

New schema for CA:
state, county, date, cases, deaths, recovered, travel_based, locally_acquired, ca_total, non_scag_total, geometry of county centroid

Still publish as public ESRI feature layer

**Comment by JeanneHolm** [comment] 2020-03-13 16:22
Thanks. These look like great additional sources and a good switch. Assume locally_acquired refers to what others call "community spread"? Are each of the counties using similar schema?

**Comment by tiffanychu90** [comment] 2020-03-13 16:25
locally_acquired is community spread. Only OC and Riverside have that info published. But since the publish it, we can scrape and keep it handy.

**Comment by ian-r-rose** [comment] 2020-03-13 16:38
@JeanneHolm Unfortunately, each of these counties are not using a similar schema. At the very least, we plan to have "Confirmed", and "Deaths" from each, and then populate the others as optional fields when available.

**Comment by JeanneHolm** [comment] 2020-03-13 16:47
Okay, focus on LA and if data elements make sense for other counties, show those, but that's only a nice to have.

**Comment by tiffanychu90** [comment] 2020-03-13 22:37
Closing this issue via our [aqueduct repo](https://github.com/CityOfLosAngeles/aqueduct) PRs:
* [Scrape county data](https://github.com/CityOfLosAngeles/aqueduct/pull/147)
* [Continually update ESRI layer with new county data.](https://github.com/CityOfLosAngeles/aqueduct/pull/148)
* [Drop duplicate observations in case we run ETL more than once per day.](https://github.com/CityOfLosAngeles/aqueduct/pull/149)
* [More docs](https://github.com/CityOfLosAngeles/aqueduct/pull/150)

**Closed as completed by tiffanychu90** 2020-03-13 22:37 UTC
